use_frameworks!

target 'FirestoreCrashRepro' do
    #pod 'Firebase/Core'
    pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'varconst/coll-opt'
    pod 'GoogleUtilities', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'varconst/coll-opt'
   pod 'FirebaseFirestore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'varconst/coll-opt'
end
